language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- pypy
install:
- pip install pytest
- pip install -e .
script:
- py.test tests
deploy:
  provider: pypi
  user: vmalloc
  password:
    secure: glT/V+E1HqJa+h+UaUzhh4Bbe/L9vE9KRPTj+5n/CD6eGTi0tZrZf3ZEbr6kv8s+FXUlLY6LlfzontsjBJNsKyixAGmSGx2p5DniKq2fH0YIj5vTiaGJvzrbQ148MDO6zcRX7nb7fXoNWpC/ioX64oOHxLQdaANkXYc7UzQ1wE/dZquUoDoXRZ008AQK7ra4P7tB0NoJlRrD6iMJh9dmH1vIvMbqhXzDe3YgXwuTxp74GtwdjTk1DpNIs4Mg2BwEtCkeht9Ys5Tpn2AnAlYxdEvxqZP5yO/z/YSIi4a/y7VxPSXwnK1Cfqilqo2wfVRHE2r9TnOwrQTDHpVpPfQExpUKpPjMFGqRWBSifEdKq++e5N46SpbciBX79VIXU2zW0TC7fNIVqoa6A1vOyatm4Jk+4yTr4unBlKtXNYArRi7iRbUke4ZAWT9wUi9sW5DeaZPeGM4/OrdeCHcEAMuqmXcXQbHJNNDRShmTqSV5ssJe/fbCALTk7vqiS+jhvxUhKn8lm2r2Jv8dRAxv34CJkSaWoIxHDkrCD9mVoTbdv0QkFsJyr38vC1xhRyrKP394njcVTiOUwOnfwzAAUChgqe925IAp+ozZSU5fRMdXBfi4Nq6UOz7PzkGLaYpwo8LlfWBbomZPJLbjfRUFbUw5jf3c6oNVRKGP8w4rQdLyfUI=
  on:
    tags: true
    repo: getslash/vintage
